# Generated by Django 2.2.5 on 2021-01-23 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, verbose_name='Имя альбома')),
                ('album_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=64, verbose_name='Жанр альбома')),
                ('cover_url', models.CharField(max_length=128, verbose_name='Путь к обложке альбома')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, verbose_name='Имя группы')),
                ('group_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, verbose_name='Путь к лейблу группы')),
                ('group_info', models.CharField(max_length=512, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='Наименование комнозиции')),
                ('track_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка к youtube видео')),
                ('album', models.ForeignKey(db_column='album', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='muzservice.Album')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'db_table': 'tracks',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='album_group',
            field=models.ForeignKey(db_column='album_group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='muzservice.Group'),
        ),
    ]
