# Generated by Django 2.2.5 on 2020-12-27 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, verbose_name='Имя альбома')),
                ('album_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('album_group', models.CharField(max_length=64, verbose_name='Группа, создавшая альбом')),
                ('genre', models.CharField(max_length=64, verbose_name='Жанр альбома')),
                ('cover_url', models.CharField(max_length=128, verbose_name='Путь к обложке альбома')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, verbose_name='Наименование комнозиции')),
                ('track_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка к youtube видео')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'db_table': 'tracks',
            },
        ),
    ]
