# Generated by Django 2.2.5 on 2020-12-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzservice', '0002_track_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album',
            new_name='album_uuid',
        ),
    ]
