# Generated by Django 2.2.5 on 2021-01-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzservice', '0002_remove_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(default='', max_length=64, verbose_name='Жанр альбома'),
            preserve_default=False,
        ),
    ]
