# Generated by Django 2.2.5 on 2020-12-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzservice', '0003_auto_20201227_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album_uuid',
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(db_column='album', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='muzservice.Album'),
        ),
    ]
